# Example configuration of access to local station for user6 on SE607.
# Edit it, rename it to access_config.yml and move to your ~/.iLiSA/ directory.
---
OBSERVING :
    observer : "Mr A. Somebody"               # Name of the observer
    project : "Testing"                       # Name of project

LCU : 
    stnid : "SE607"                           # Station ID
    user : "user6"                            # username on LCU (all LCU processes will run as this)
    hostname : "se607c"                       # internet hostname of LCU
    home : "/data/home/user6/"                # user's home directory on LCU 
    dumpdir : "/data/home/user6/dump_data/"   # LCU directory where (e.g. statistics) data is dumped
    DryRun : false                            # Whether to a dryrun of observations
    usescriptonlcu : false                    # Use dedicated scripts on LCU (old).

DPU:        # This is the machine where LCU data ends up and might process it
  LOFARdataArchive : "/data/username/lofar/"  # Top path to final data archive
  BeamFormDataDir :  "/mnt/lane?/BF/SE607/"
  BeamFormPort0 :    "4346"
  BeamFormLogFile :  "/mnt/lane0/logs/BFdump.log"
  TBBraw2h5Cmd : "/home/username/sw/TBBraw2h5-pack/source/build/src/apps/TBBraw2h5" # Path to TBBraw2h5
  TBBh5dumpDir :     "/data/username/lofar/tbb/h5/"
...
